### ISSUE TITLE
EPIC: Print Preview

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-translate#198]
The goal of this epic is to Add saving PDF to gT. 

The print icon should be added to the top of the card:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFVDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d278b23af20bc9dca4fe66238433bf995e9b2d1/CleanShot%202023-10-04%20at%2006.31.16.png)

The user should be offered some basic layout options like double column and double spacing, margins and page size:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMndDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6873e17fa322e0ac28e2e723c37224a2ae67b5d4/CleanShot%202023-10-04%20at%2006.14.40.png)

The user should be presented with a typical print dialog:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjBDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c05671bfc68f8f77c800833e15b34ed63404526/CleanShot%202023-10-04%20at%2006.13.13.png)

**Comment by birchamp** [comment]
@birchamp do mockup of UI

**Comment by larsgson** [comment]
This new print preview feature will need some work in three places - and then the same code will become useful in different places.
The main solution is to be implemented here:
https://github.com/unfoldingWord/oce-editor-tools/issues/68

followed by connecting this to the gateway UI
https://github.com/unfoldingWord/gateway-translate/issues/211

and also writing some additional navigation code in order to include this print preview code also for a Door43 preview
