### ISSUE TITLE
Failed to load the scripture card after login-in back

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-translate#78]
1. Login to the app, open a new book and make some edits and save.
2. Logout
3. Log back in and Note that the scripture card added in step 1 shows blank. See the errors in the console:
![Screenshot 2022-11-10 at 9.07.45 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/c5064589-6589-4b10-854d-a0cc5eab9b32)
<img width="1431" alt="Screenshot 2022-11-10 at 12 12 04 PM" src="https://user-images.githubusercontent.com/51806180/201162141-07045afd-3303-4cfd-878f-4341af8cd84f.png">

**Comment by mandolyte** [comment]
@larsgson I think this case is the best reason to consider exposing actions via the pk cache context. In this case, we need a way to remove everything in the cache when the user logs out.

Apparently, things are "sticking" around. This symptom is now probably the root cause of several bugs right now:
- #67 (gT)
- #40 (uw-editor)
- #78 (gT)
- #44 (uw-editor)

**Comment by elsylambert** [comment]
Not seeing this problem in v0.0.18 build cc1f350. After logging back in, users can see their edited and saved Book Cards.

**Comment by danielklapp** [comment]
Testing with v0.9.0-rc.2 build 29a2450 QA. Looks good
